#!/bin/bash

hostnamectl set-hostname loh.ebaniy.net

mkdir -p /etc/net/ifaces/ens18
echo "172.16.4.2/30" > /etc/net/ifaces/ens18/ipv4address
echo "nameserver 77.88.8.8" > /etc/net/ifaces/ens18/resolv.conf
echo "default via 172.16.4.1" > /etc/net/ifaces/ens18/ipv4route
